name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ netcoreapp3.1, net5.0 ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./tests/WaySON.UnitTests/
        dotnet test --framework=${{ matrix.dotnet }} --no-restore /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/wayfair-text-json/wayfair-text-json/ /p:CoverletOutputFormat=opencover
    - name: Publish Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: /home/runner/work/wayfair-text-json/wayfair-text-json/coverage.${{ matrix.dotnet }}.opencover.xml
        fail_ci_if_error: true
