name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./tests/WaySON.UnitTests/
        dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/WaySON/WaySON/ /p:CoverletOutputFormat=opencover
    - name: Publish Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: /home/runner/work/WaySON/WaySON/coverage.opencover.xml
        fail_ci_if_error: true
