name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./tests/Wayfair.Text.Json.UnitTests/
        dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestCoverage/ /p:CoverletOutputFormat=lcov

    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        directory: ./tests/Wayfair.Text.Json.UnitTests/TestCoverage
        fail_ci_if_error: true
        verbose: true
